repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
        files: \.(py|md|txt)$
      - id: end-of-file-fixer
        files: \.(py|md|txt)$
      - id: check-yaml
        files: \.yaml$
      - id: check-added-large-files
        files: \.(py|md|txt|yaml)$

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
        files: ^(src|tests|scripts)/.*\.py$

  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings]
        files: ^(src|tests|scripts)/.*\.py$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        additional_dependencies: [types-requests]
        files: ^(src|tests|scripts)/.*\.py$
